#!/usr/bin/env python3
"""Sync the changelog and repository pages from polarizetech's public work repos.

Writes, and never by hand:

  _data/changelog.json    merged pull requests, newest first: repo, number, title,
                          body (the PR description, markdown), url, merged_at
  _data/repos.json        every included repo: name, description, links, language,
                          licence, stars, its latest merged PR, when it was last
                          active, and its README (markdown, relative links
                          rewritten to absolute GitHub URLs)
  changelog/index.html,   the paginated changelog (PER_PAGE entries a page).
  changelog/pageN/        GitHub Pages' only paginator cannot page a data file, so
                          the pages are generated here; each is a stub that
                          _layouts/changelog.html renders.
  work/<repo>/            one feature page per repo, a stub for _layouts/repo.html.
                          (The /work/ index itself is hand-written: work/index.html.)

Stubs this script generated and no longer needs (a repo gone private, fewer
pages) are removed; a file without the GENERATED marker is never touched.

JSON rather than YAML on purpose: PR bodies and READMEs are multi-line markdown,
and an unclosed YAML scalar is exactly what broke a Pages deploy before
(validate_posts.py RULE 0).

Usage:  python3 scripts/sync_changelog.py [--org polarizetech] [--check]
        --check   exit 1 if anything would change, write nothing
        GITHUB_TOKEN in the environment raises the rate limit; not required.
"""
import argparse
import json
import math
import os
import re
import shutil
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import SITE

PER_PAGE = 10
# Public repos that are not "work". The site itself is left out of Work and the
# changelog alike because its history is already on every post's version drawer.
EXCLUDE = {'polarize.tech', '.github'}
MARKER = 'GENERATED by scripts/sync_changelog.py'
CHANGELOG_DIR = SITE / 'changelog'
WORK_DIR = SITE / 'work'


def api(path, raw=False):
    url = path if path.startswith('http') else f'https://api.github.com{path}'
    req = urllib.request.Request(url, headers={
        'Accept': 'application/vnd.github.raw' if raw else 'application/vnd.github+json',
        'User-Agent': 'polarize.tech-changelog'})
    if os.environ.get('GITHUB_TOKEN'):
        req.add_header('Authorization', f'Bearer {os.environ["GITHUB_TOKEN"]}')
    with urllib.request.urlopen(req, timeout=30) as r:
        body = r.read().decode('utf-8')
    return body if raw else json.loads(body)


# Relative links and images in a README or PR body point into the repo; on this
# site they would 404. Rewrite them to the repo on GitHub.
MD_LINK = re.compile(r'(!?)\[([^\]]*)\]\((?!https?:|mailto:|#|/)([^)\s]+)([^)]*)\)')
HTML_SRC = re.compile(r'''(src|href)=(["'])(?!https?:|mailto:|#|/|data:)([^"']+)\2''')


def absolutize(md, org, repo, branch):
    blob = f'https://github.com/{org}/{repo}/blob/{branch}/'
    raw = f'https://raw.githubusercontent.com/{org}/{repo}/{branch}/'
    md = MD_LINK.sub(lambda m: f'{m[1]}[{m[2]}]({(raw if m[1] else blob) + m[3].lstrip("./")}{m[4]})', md)
    return HTML_SRC.sub(lambda m: f'{m[1]}={m[2]}{(raw if m[1] == "src" else blob) + m[3].lstrip("./")}{m[2]}', md)


def strip_title(md):
    """Drop a README's leading H1 — the page already shows the repo name."""
    return re.sub(r'\A\s*(#\s+[^\n]*\n|[^\n]+\n=+\s*\n)', '', md, count=1).lstrip('\n')


def fetch_repos(org):
    repos = []
    for r in api(f'/orgs/{org}/repos?type=public&per_page=100&sort=pushed'):
        if r.get('private') or r.get('archived') or r['name'] in EXCLUDE:
            continue
        try:
            readme = api(f'/repos/{org}/{r["name"]}/readme', raw=True)
            readme = strip_title(absolutize(readme, org, r['name'], r['default_branch']))
        except urllib.error.HTTPError:
            readme = ''
        repos.append({
            'name': r['name'],
            'description': r['description'] or '',
            'url': r['html_url'],
            'homepage': r['homepage'] or '',
            'language': r['language'] or '',
            'license': (r.get('license') or {}).get('spdx_id') or '',
            'stars': r['stargazers_count'],
            'topics': r.get('topics') or [],
            'branch': r['default_branch'],
            'created_at': r['created_at'],
            'pushed_at': r['pushed_at'],
            'readme': readme,
        })
    repos.sort(key=lambda r: r['name'])
    return repos


def fetch_changes(org, repos):
    branches = {r['name']: r['branch'] for r in repos}
    q = urllib.parse.urlencode({'q': f'org:{org} is:pr is:merged is:public',
                                'sort': 'updated', 'order': 'desc', 'per_page': 100})
    rows = []
    for i in api(f'/search/issues?{q}')['items']:
        merged = (i.get('pull_request') or {}).get('merged_at')
        repo = i['repository_url'].rsplit('/', 1)[-1]
        if not merged or repo not in branches:
            continue
        rows.append({
            'repo': repo,
            'number': i['number'],
            'title': ' '.join(i['title'].split()),
            'body': absolutize((i['body'] or '').strip(), org, repo, branches[repo]),
            'url': i['html_url'],
            'merged_at': merged,
        })
    rows.sort(key=lambda r: r['merged_at'], reverse=True)
    return rows


def stub(front):
    lines = ['---'] + [f'{k}: {json.dumps(v, ensure_ascii=False)}' for k, v in front.items()] + ['---',
             f'<!-- {MARKER} — do not edit; re-run the script. -->', '']
    return '\n'.join(lines)


def plan(org, changes, repos):
    """Every file this script owns, path -> content."""
    files = {
        SITE / '_data' / 'changelog.json': json.dumps(changes, indent=1, ensure_ascii=False) + '\n',
        SITE / '_data' / 'repos.json': json.dumps(repos, indent=1, ensure_ascii=False) + '\n',
    }
    pages = max(1, math.ceil(len(changes) / PER_PAGE))
    for n in range(1, pages + 1):
        path = CHANGELOG_DIR / ('index.html' if n == 1 else f'page{n}/index.html')
        files[path] = stub({
            'layout': 'changelog', 'title': 'Changelog', 'section': 'changelog',
            'description': f'Merged pull requests across the public {org} repositories, newest first.',
            'page_num': n, 'total_pages': pages, 'per_page': PER_PAGE,
            'permalink': '/changelog/' if n == 1 else f'/changelog/page{n}/'})
    for r in repos:
        files[WORK_DIR / r['name'] / 'index.html'] = stub({
            'layout': 'repo', 'title': r['name'], 'section': 'work', 'repo': r['name'],
            'description': r['description'], 'permalink': f'/work/{r["name"]}/'})
    return files


def owned_stubs():
    return [p for d in (CHANGELOG_DIR, WORK_DIR) if d.exists()
            for p in d.rglob('index.html') if MARKER in p.read_text()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--org', default='polarizetech')
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    repos = fetch_repos(args.org)
    changes = fetch_changes(args.org, repos)
    # Each repo's latest merged PR, and when it was last active — the home page
    # highlights repos by recent activity, each with its latest change.
    for r in repos:
        latest = next((c for c in changes if c['repo'] == r['name']), None)
        r['latest_change'] = ({k: latest[k] for k in ('number', 'title', 'url', 'merged_at')}
                              if latest else None)
        r['active_at'] = latest['merged_at'] if latest else r['pushed_at']
    files = plan(args.org, changes, repos)
    stale = [p for p in owned_stubs() if p not in files]
    changed = [p for p, text in files.items() if not p.exists() or p.read_text() != text]

    if args.check:
        for p in changed + stale:
            print(f'STALE  {p.relative_to(SITE)}', file=sys.stderr)
        if changed or stale:
            print('run scripts/sync_changelog.py', file=sys.stderr)
            return 1
        print('OK    changelog and repo pages are current')
        return 0

    for p in changed:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(files[p])
        print(f'WROTE {p.relative_to(SITE)}')
    for p in stale:
        p.unlink()
        if p.parent not in (CHANGELOG_DIR, WORK_DIR) and not any(p.parent.iterdir()):
            shutil.rmtree(p.parent)
        print(f'REMOVED {p.relative_to(SITE)}')
    if not changed and not stale:
        print('OK    nothing changed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
